[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://determined-hermann-b8609f.netlify.com/*"
  to = "https://mykmal.xyz/:splat"
  status = 301!
  force = false
